apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: task-management
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: backend
          image: registry.digitalocean.com/kkura/task-backend:backend-latest
