apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task-management
resources:
  - ../../base
  - ingress.yaml
patches:
  - path: backend-deployment-patch.yaml
  - path: frontend-deployment-patch.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: registry-credentials
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson
  - name: backend-secrets
    behavior: replace
    envs:
      - backend-secret.env
