apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task-management
resources:
  - ../../base
  - ingress.yaml
patches:
  - path: backend-deployment-patch.yaml
  - path: frontend-deployment-patch.yaml
