apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: task-management
  labels:
    app.kubernetes.io/name: task-backend
    app.kubernetes.io/part-of: task-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: task-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: task-backend
        app.kubernetes.io/part-of: task-management
    spec:
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - name: backend
          image: registry.digitalocean.com/kkura/task-backend:backend-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: PORT
            - name: OPENAI_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: OPENAI_BASE_URL
            - name: OPENAI_TASK_DRAFT_MODEL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: OPENAI_TASK_DRAFT_MODEL
            - name: OPENAI_MODEL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: OPENAI_MODEL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_SECRET
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: OPENAI_API_KEY
          readinessProbe:
            httpGet:
              path: /?query=%7B__typename%7D
              port: 4000
              httpHeaders:
                - name: apollo-require-preflight
                  value: "true"
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /?query=%7B__typename%7D
              port: 4000
              httpHeaders:
                - name: apollo-require-preflight
                  value: "true"
            initialDelaySeconds: 30
            periodSeconds: 20
      restartPolicy: Always
