apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: task-management
  labels:
    app.kubernetes.io/name: task-backend
    app.kubernetes.io/part-of: task-management
spec:
  selector:
    app.kubernetes.io/name: task-backend
  ports:
    - name: http
      port: 4000
      targetPort: 4000
    - name: realtime
      port: 4001
      targetPort: 4001
  type: ClusterIP
