apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: task-management
  labels:
    app.kubernetes.io/name: task-frontend
    app.kubernetes.io/part-of: task-management
spec:
  selector:
    app.kubernetes.io/name: task-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
