apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task-management
resources:
  - namespace.yaml
  - backend-configmap.yaml
  - backend-secret.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
