apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: task-management
resources:
  - namespace.yaml
  - backend-configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - redis.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: backend-secrets
    envs:
      - backend-secret.env
